/* Generated by tools/gen_winmm.py from the system's 32-bit winmm.dll. Do not edit. */
#define WINMM_THUNKS 187
static const struct { const char* name; WORD ordinal; } g_thunkTargets[WINMM_THUNKS]={
    {NULL,2},
    {"mciExecute",3},
    {"CloseDriver",4},
    {"DefDriverProc",5},
    {"DriverCallback",6},
    {"DrvGetModuleHandle",7},
    {"GetDriverModuleHandle",8},
    {"NotifyCallbackData",9},
    {"OpenDriver",10},
    {"PlaySound",11},
    {"PlaySoundA",12},
    {"PlaySoundW",13},
    {"SendDriverMessage",14},
    {"WOW32DriverCallback",15},
    {"WOW32ResolveMultiMediaHandle",16},
    {"WOWAppExit",17},
    {"aux32Message",18},
    {"auxGetDevCapsW",20},
    {"auxOutMessage",23},
    {"joy32Message",25},
    {"joyConfigChanged",26},
    {"joyGetDevCapsA",27},
    {"joyGetDevCapsW",28},
    {"joyGetNumDevs",29},
    {"joyGetPos",30},
    {"joyGetPosEx",31},
    {"joyGetThreshold",32},
    {"joyReleaseCapture",33},
    {"joySetCapture",34},
    {"joySetThreshold",35},
    {"mci32Message",36},
    {"mciDriverNotify",37},
    {"mciDriverYield",38},
    {"mciFreeCommandResource",39},
    {"mciGetCreatorTask",40},
    {"mciGetDeviceIDA",41},
    {"mciGetDeviceIDFromElementIDA",42},
    {"mciGetDeviceIDFromElementIDW",43},
    {"mciGetDeviceIDW",44},
    {"mciGetDriverData",45},
    {"mciGetErrorStringA",46},
    {"mciGetErrorStringW",47},
    {"mciGetYieldProc",48},
    {"mciLoadCommandResource",49},
    {"mciSendCommandW",51},
    {"mciSendStringW",53},
    {"mciSetDriverData",54},
    {"mciSetYieldProc",55},
    {"mid32Message",56},
    {"midiConnect",57},
    {"midiDisconnect",58},
    {"midiInAddBuffer",59},
    {"midiInClose",60},
    {"midiInGetDevCapsA",61},
    {"midiInGetDevCapsW",62},
    {"midiInGetErrorTextA",63},
    {"midiInGetErrorTextW",64},
    {"midiInGetID",65},
    {"midiInGetNumDevs",66},
    {"midiInMessage",67},
    {"midiInOpen",68},
    {"midiInPrepareHeader",69},
    {"midiInReset",70},
    {"midiInStart",71},
    {"midiInStop",72},
    {"midiInUnprepareHeader",73},
    {"midiOutCacheDrumPatches",74},
    {"midiOutCachePatches",75},
    {"midiOutClose",76},
    {"midiOutGetDevCapsA",77},
    {"midiOutGetDevCapsW",78},
    {"midiOutGetErrorTextA",79},
    {"midiOutGetErrorTextW",80},
    {"midiOutGetID",81},
    {"midiOutGetNumDevs",82},
    {"midiOutGetVolume",83},
    {"midiOutLongMsg",84},
    {"midiOutMessage",85},
    {"midiOutOpen",86},
    {"midiOutPrepareHeader",87},
    {"midiOutReset",88},
    {"midiOutSetVolume",89},
    {"midiOutShortMsg",90},
    {"midiOutUnprepareHeader",91},
    {"midiStreamClose",92},
    {"midiStreamOpen",93},
    {"midiStreamOut",94},
    {"midiStreamPause",95},
    {"midiStreamPosition",96},
    {"midiStreamProperty",97},
    {"midiStreamRestart",98},
    {"midiStreamStop",99},
    {"mixerClose",100},
    {"mixerGetControlDetailsA",101},
    {"mixerGetControlDetailsW",102},
    {"mixerGetDevCapsA",103},
    {"mixerGetDevCapsW",104},
    {"mixerGetID",105},
    {"mixerGetLineControlsA",106},
    {"mixerGetLineControlsW",107},
    {"mixerGetLineInfoA",108},
    {"mixerGetLineInfoW",109},
    {"mixerGetNumDevs",110},
    {"mixerMessage",111},
    {"mixerOpen",112},
    {"mixerSetControlDetails",113},
    {"mmDrvInstall",114},
    {"mmGetCurrentTask",115},
    {"mmTaskBlock",116},
    {"mmTaskCreate",117},
    {"mmTaskSignal",118},
    {"mmTaskYield",119},
    {"mmioAdvance",120},
    {"mmioAscend",121},
    {"mmioClose",122},
    {"mmioCreateChunk",123},
    {"mmioDescend",124},
    {"mmioFlush",125},
    {"mmioGetInfo",126},
    {"mmioInstallIOProcA",127},
    {"mmioInstallIOProcW",128},
    {"mmioOpenA",129},
    {"mmioOpenW",130},
    {"mmioRead",131},
    {"mmioRenameA",132},
    {"mmioRenameW",133},
    {"mmioSeek",134},
    {"mmioSendMessage",135},
    {"mmioSetBuffer",136},
    {"mmioSetInfo",137},
    {"mmioStringToFOURCCA",138},
    {"mmioStringToFOURCCW",139},
    {"mmioWrite",140},
    {"mmsystemGetVersion",141},
    {"mod32Message",142},
    {"mxd32Message",143},
    {"sndPlaySoundA",144},
    {"sndPlaySoundW",145},
    {"tid32Message",146},
    {"timeBeginPeriod",147},
    {"timeEndPeriod",148},
    {"timeGetDevCaps",149},
    {"timeGetSystemTime",150},
    {"timeGetTime",151},
    {"timeKillEvent",152},
    {"timeSetEvent",153},
    {"waveInAddBuffer",154},
    {"waveInClose",155},
    {"waveInGetDevCapsA",156},
    {"waveInGetDevCapsW",157},
    {"waveInGetErrorTextA",158},
    {"waveInGetErrorTextW",159},
    {"waveInGetID",160},
    {"waveInGetNumDevs",161},
    {"waveInGetPosition",162},
    {"waveInMessage",163},
    {"waveInOpen",164},
    {"waveInPrepareHeader",165},
    {"waveInReset",166},
    {"waveInStart",167},
    {"waveInStop",168},
    {"waveInUnprepareHeader",169},
    {"waveOutBreakLoop",170},
    {"waveOutClose",171},
    {"waveOutGetDevCapsA",172},
    {"waveOutGetDevCapsW",173},
    {"waveOutGetErrorTextA",174},
    {"waveOutGetErrorTextW",175},
    {"waveOutGetID",176},
    {"waveOutGetNumDevs",177},
    {"waveOutGetPitch",178},
    {"waveOutGetPlaybackRate",179},
    {"waveOutGetPosition",180},
    {"waveOutGetVolume",181},
    {"waveOutMessage",182},
    {"waveOutOpen",183},
    {"waveOutPause",184},
    {"waveOutPrepareHeader",185},
    {"waveOutReset",186},
    {"waveOutRestart",187},
    {"waveOutSetPitch",188},
    {"waveOutSetPlaybackRate",189},
    {"waveOutSetVolume",190},
    {"waveOutUnprepareHeader",191},
    {"waveOutWrite",192},
    {"wid32Message",193},
    {"wod32Message",194},
};
void* g_real[WINMM_THUNKS];
__asm__(".text\n"
    ".globl _thunk_0\n_thunk_0: jmp *_g_real+0\n"
    ".globl _thunk_1\n_thunk_1: jmp *_g_real+4\n"
    ".globl _thunk_2\n_thunk_2: jmp *_g_real+8\n"
    ".globl _thunk_3\n_thunk_3: jmp *_g_real+12\n"
    ".globl _thunk_4\n_thunk_4: jmp *_g_real+16\n"
    ".globl _thunk_5\n_thunk_5: jmp *_g_real+20\n"
    ".globl _thunk_6\n_thunk_6: jmp *_g_real+24\n"
    ".globl _thunk_7\n_thunk_7: jmp *_g_real+28\n"
    ".globl _thunk_8\n_thunk_8: jmp *_g_real+32\n"
    ".globl _thunk_9\n_thunk_9: jmp *_g_real+36\n"
    ".globl _thunk_10\n_thunk_10: jmp *_g_real+40\n"
    ".globl _thunk_11\n_thunk_11: jmp *_g_real+44\n"
    ".globl _thunk_12\n_thunk_12: jmp *_g_real+48\n"
    ".globl _thunk_13\n_thunk_13: jmp *_g_real+52\n"
    ".globl _thunk_14\n_thunk_14: jmp *_g_real+56\n"
    ".globl _thunk_15\n_thunk_15: jmp *_g_real+60\n"
    ".globl _thunk_16\n_thunk_16: jmp *_g_real+64\n"
    ".globl _thunk_17\n_thunk_17: jmp *_g_real+68\n"
    ".globl _thunk_18\n_thunk_18: jmp *_g_real+72\n"
    ".globl _thunk_19\n_thunk_19: jmp *_g_real+76\n"
    ".globl _thunk_20\n_thunk_20: jmp *_g_real+80\n"
    ".globl _thunk_21\n_thunk_21: jmp *_g_real+84\n"
    ".globl _thunk_22\n_thunk_22: jmp *_g_real+88\n"
    ".globl _thunk_23\n_thunk_23: jmp *_g_real+92\n"
    ".globl _thunk_24\n_thunk_24: jmp *_g_real+96\n"
    ".globl _thunk_25\n_thunk_25: jmp *_g_real+100\n"
    ".globl _thunk_26\n_thunk_26: jmp *_g_real+104\n"
    ".globl _thunk_27\n_thunk_27: jmp *_g_real+108\n"
    ".globl _thunk_28\n_thunk_28: jmp *_g_real+112\n"
    ".globl _thunk_29\n_thunk_29: jmp *_g_real+116\n"
    ".globl _thunk_30\n_thunk_30: jmp *_g_real+120\n"
    ".globl _thunk_31\n_thunk_31: jmp *_g_real+124\n"
    ".globl _thunk_32\n_thunk_32: jmp *_g_real+128\n"
    ".globl _thunk_33\n_thunk_33: jmp *_g_real+132\n"
    ".globl _thunk_34\n_thunk_34: jmp *_g_real+136\n"
    ".globl _thunk_35\n_thunk_35: jmp *_g_real+140\n"
    ".globl _thunk_36\n_thunk_36: jmp *_g_real+144\n"
    ".globl _thunk_37\n_thunk_37: jmp *_g_real+148\n"
    ".globl _thunk_38\n_thunk_38: jmp *_g_real+152\n"
    ".globl _thunk_39\n_thunk_39: jmp *_g_real+156\n"
    ".globl _thunk_40\n_thunk_40: jmp *_g_real+160\n"
    ".globl _thunk_41\n_thunk_41: jmp *_g_real+164\n"
    ".globl _thunk_42\n_thunk_42: jmp *_g_real+168\n"
    ".globl _thunk_43\n_thunk_43: jmp *_g_real+172\n"
    ".globl _thunk_44\n_thunk_44: jmp *_g_real+176\n"
    ".globl _thunk_45\n_thunk_45: jmp *_g_real+180\n"
    ".globl _thunk_46\n_thunk_46: jmp *_g_real+184\n"
    ".globl _thunk_47\n_thunk_47: jmp *_g_real+188\n"
    ".globl _thunk_48\n_thunk_48: jmp *_g_real+192\n"
    ".globl _thunk_49\n_thunk_49: jmp *_g_real+196\n"
    ".globl _thunk_50\n_thunk_50: jmp *_g_real+200\n"
    ".globl _thunk_51\n_thunk_51: jmp *_g_real+204\n"
    ".globl _thunk_52\n_thunk_52: jmp *_g_real+208\n"
    ".globl _thunk_53\n_thunk_53: jmp *_g_real+212\n"
    ".globl _thunk_54\n_thunk_54: jmp *_g_real+216\n"
    ".globl _thunk_55\n_thunk_55: jmp *_g_real+220\n"
    ".globl _thunk_56\n_thunk_56: jmp *_g_real+224\n"
    ".globl _thunk_57\n_thunk_57: jmp *_g_real+228\n"
    ".globl _thunk_58\n_thunk_58: jmp *_g_real+232\n"
    ".globl _thunk_59\n_thunk_59: jmp *_g_real+236\n"
    ".globl _thunk_60\n_thunk_60: jmp *_g_real+240\n"
    ".globl _thunk_61\n_thunk_61: jmp *_g_real+244\n"
    ".globl _thunk_62\n_thunk_62: jmp *_g_real+248\n"
    ".globl _thunk_63\n_thunk_63: jmp *_g_real+252\n"
    ".globl _thunk_64\n_thunk_64: jmp *_g_real+256\n"
    ".globl _thunk_65\n_thunk_65: jmp *_g_real+260\n"
    ".globl _thunk_66\n_thunk_66: jmp *_g_real+264\n"
    ".globl _thunk_67\n_thunk_67: jmp *_g_real+268\n"
    ".globl _thunk_68\n_thunk_68: jmp *_g_real+272\n"
    ".globl _thunk_69\n_thunk_69: jmp *_g_real+276\n"
    ".globl _thunk_70\n_thunk_70: jmp *_g_real+280\n"
    ".globl _thunk_71\n_thunk_71: jmp *_g_real+284\n"
    ".globl _thunk_72\n_thunk_72: jmp *_g_real+288\n"
    ".globl _thunk_73\n_thunk_73: jmp *_g_real+292\n"
    ".globl _thunk_74\n_thunk_74: jmp *_g_real+296\n"
    ".globl _thunk_75\n_thunk_75: jmp *_g_real+300\n"
    ".globl _thunk_76\n_thunk_76: jmp *_g_real+304\n"
    ".globl _thunk_77\n_thunk_77: jmp *_g_real+308\n"
    ".globl _thunk_78\n_thunk_78: jmp *_g_real+312\n"
    ".globl _thunk_79\n_thunk_79: jmp *_g_real+316\n"
    ".globl _thunk_80\n_thunk_80: jmp *_g_real+320\n"
    ".globl _thunk_81\n_thunk_81: jmp *_g_real+324\n"
    ".globl _thunk_82\n_thunk_82: jmp *_g_real+328\n"
    ".globl _thunk_83\n_thunk_83: jmp *_g_real+332\n"
    ".globl _thunk_84\n_thunk_84: jmp *_g_real+336\n"
    ".globl _thunk_85\n_thunk_85: jmp *_g_real+340\n"
    ".globl _thunk_86\n_thunk_86: jmp *_g_real+344\n"
    ".globl _thunk_87\n_thunk_87: jmp *_g_real+348\n"
    ".globl _thunk_88\n_thunk_88: jmp *_g_real+352\n"
    ".globl _thunk_89\n_thunk_89: jmp *_g_real+356\n"
    ".globl _thunk_90\n_thunk_90: jmp *_g_real+360\n"
    ".globl _thunk_91\n_thunk_91: jmp *_g_real+364\n"
    ".globl _thunk_92\n_thunk_92: jmp *_g_real+368\n"
    ".globl _thunk_93\n_thunk_93: jmp *_g_real+372\n"
    ".globl _thunk_94\n_thunk_94: jmp *_g_real+376\n"
    ".globl _thunk_95\n_thunk_95: jmp *_g_real+380\n"
    ".globl _thunk_96\n_thunk_96: jmp *_g_real+384\n"
    ".globl _thunk_97\n_thunk_97: jmp *_g_real+388\n"
    ".globl _thunk_98\n_thunk_98: jmp *_g_real+392\n"
    ".globl _thunk_99\n_thunk_99: jmp *_g_real+396\n"
    ".globl _thunk_100\n_thunk_100: jmp *_g_real+400\n"
    ".globl _thunk_101\n_thunk_101: jmp *_g_real+404\n"
    ".globl _thunk_102\n_thunk_102: jmp *_g_real+408\n"
    ".globl _thunk_103\n_thunk_103: jmp *_g_real+412\n"
    ".globl _thunk_104\n_thunk_104: jmp *_g_real+416\n"
    ".globl _thunk_105\n_thunk_105: jmp *_g_real+420\n"
    ".globl _thunk_106\n_thunk_106: jmp *_g_real+424\n"
    ".globl _thunk_107\n_thunk_107: jmp *_g_real+428\n"
    ".globl _thunk_108\n_thunk_108: jmp *_g_real+432\n"
    ".globl _thunk_109\n_thunk_109: jmp *_g_real+436\n"
    ".globl _thunk_110\n_thunk_110: jmp *_g_real+440\n"
    ".globl _thunk_111\n_thunk_111: jmp *_g_real+444\n"
    ".globl _thunk_112\n_thunk_112: jmp *_g_real+448\n"
    ".globl _thunk_113\n_thunk_113: jmp *_g_real+452\n"
    ".globl _thunk_114\n_thunk_114: jmp *_g_real+456\n"
    ".globl _thunk_115\n_thunk_115: jmp *_g_real+460\n"
    ".globl _thunk_116\n_thunk_116: jmp *_g_real+464\n"
    ".globl _thunk_117\n_thunk_117: jmp *_g_real+468\n"
    ".globl _thunk_118\n_thunk_118: jmp *_g_real+472\n"
    ".globl _thunk_119\n_thunk_119: jmp *_g_real+476\n"
    ".globl _thunk_120\n_thunk_120: jmp *_g_real+480\n"
    ".globl _thunk_121\n_thunk_121: jmp *_g_real+484\n"
    ".globl _thunk_122\n_thunk_122: jmp *_g_real+488\n"
    ".globl _thunk_123\n_thunk_123: jmp *_g_real+492\n"
    ".globl _thunk_124\n_thunk_124: jmp *_g_real+496\n"
    ".globl _thunk_125\n_thunk_125: jmp *_g_real+500\n"
    ".globl _thunk_126\n_thunk_126: jmp *_g_real+504\n"
    ".globl _thunk_127\n_thunk_127: jmp *_g_real+508\n"
    ".globl _thunk_128\n_thunk_128: jmp *_g_real+512\n"
    ".globl _thunk_129\n_thunk_129: jmp *_g_real+516\n"
    ".globl _thunk_130\n_thunk_130: jmp *_g_real+520\n"
    ".globl _thunk_131\n_thunk_131: jmp *_g_real+524\n"
    ".globl _thunk_132\n_thunk_132: jmp *_g_real+528\n"
    ".globl _thunk_133\n_thunk_133: jmp *_g_real+532\n"
    ".globl _thunk_134\n_thunk_134: jmp *_g_real+536\n"
    ".globl _thunk_135\n_thunk_135: jmp *_g_real+540\n"
    ".globl _thunk_136\n_thunk_136: jmp *_g_real+544\n"
    ".globl _thunk_137\n_thunk_137: jmp *_g_real+548\n"
    ".globl _thunk_138\n_thunk_138: jmp *_g_real+552\n"
    ".globl _thunk_139\n_thunk_139: jmp *_g_real+556\n"
    ".globl _thunk_140\n_thunk_140: jmp *_g_real+560\n"
    ".globl _thunk_141\n_thunk_141: jmp *_g_real+564\n"
    ".globl _thunk_142\n_thunk_142: jmp *_g_real+568\n"
    ".globl _thunk_143\n_thunk_143: jmp *_g_real+572\n"
    ".globl _thunk_144\n_thunk_144: jmp *_g_real+576\n"
    ".globl _thunk_145\n_thunk_145: jmp *_g_real+580\n"
    ".globl _thunk_146\n_thunk_146: jmp *_g_real+584\n"
    ".globl _thunk_147\n_thunk_147: jmp *_g_real+588\n"
    ".globl _thunk_148\n_thunk_148: jmp *_g_real+592\n"
    ".globl _thunk_149\n_thunk_149: jmp *_g_real+596\n"
    ".globl _thunk_150\n_thunk_150: jmp *_g_real+600\n"
    ".globl _thunk_151\n_thunk_151: jmp *_g_real+604\n"
    ".globl _thunk_152\n_thunk_152: jmp *_g_real+608\n"
    ".globl _thunk_153\n_thunk_153: jmp *_g_real+612\n"
    ".globl _thunk_154\n_thunk_154: jmp *_g_real+616\n"
    ".globl _thunk_155\n_thunk_155: jmp *_g_real+620\n"
    ".globl _thunk_156\n_thunk_156: jmp *_g_real+624\n"
    ".globl _thunk_157\n_thunk_157: jmp *_g_real+628\n"
    ".globl _thunk_158\n_thunk_158: jmp *_g_real+632\n"
    ".globl _thunk_159\n_thunk_159: jmp *_g_real+636\n"
    ".globl _thunk_160\n_thunk_160: jmp *_g_real+640\n"
    ".globl _thunk_161\n_thunk_161: jmp *_g_real+644\n"
    ".globl _thunk_162\n_thunk_162: jmp *_g_real+648\n"
    ".globl _thunk_163\n_thunk_163: jmp *_g_real+652\n"
    ".globl _thunk_164\n_thunk_164: jmp *_g_real+656\n"
    ".globl _thunk_165\n_thunk_165: jmp *_g_real+660\n"
    ".globl _thunk_166\n_thunk_166: jmp *_g_real+664\n"
    ".globl _thunk_167\n_thunk_167: jmp *_g_real+668\n"
    ".globl _thunk_168\n_thunk_168: jmp *_g_real+672\n"
    ".globl _thunk_169\n_thunk_169: jmp *_g_real+676\n"
    ".globl _thunk_170\n_thunk_170: jmp *_g_real+680\n"
    ".globl _thunk_171\n_thunk_171: jmp *_g_real+684\n"
    ".globl _thunk_172\n_thunk_172: jmp *_g_real+688\n"
    ".globl _thunk_173\n_thunk_173: jmp *_g_real+692\n"
    ".globl _thunk_174\n_thunk_174: jmp *_g_real+696\n"
    ".globl _thunk_175\n_thunk_175: jmp *_g_real+700\n"
    ".globl _thunk_176\n_thunk_176: jmp *_g_real+704\n"
    ".globl _thunk_177\n_thunk_177: jmp *_g_real+708\n"
    ".globl _thunk_178\n_thunk_178: jmp *_g_real+712\n"
    ".globl _thunk_179\n_thunk_179: jmp *_g_real+716\n"
    ".globl _thunk_180\n_thunk_180: jmp *_g_real+720\n"
    ".globl _thunk_181\n_thunk_181: jmp *_g_real+724\n"
    ".globl _thunk_182\n_thunk_182: jmp *_g_real+728\n"
    ".globl _thunk_183\n_thunk_183: jmp *_g_real+732\n"
    ".globl _thunk_184\n_thunk_184: jmp *_g_real+736\n"
    ".globl _thunk_185\n_thunk_185: jmp *_g_real+740\n"
    ".globl _thunk_186\n_thunk_186: jmp *_g_real+744\n"
);
