/* winmm.dll for the GOG release of Interstate '82.
 *
 * GOG ships its own winmm.dll ("ogg-winmm virtual CD") that plays the
 * soundtrack from MUSIC\TrackNN.ogg in place of the CD audio tracks. It
 * passes every other winmm function on through the relative forwarder
 * system32\\winmm.<name>, and on current Windows 11 resolving those forwarders
 * hangs the game before it opens a window. It also plays the music through
 * waveOut, next to which the game's DirectSound effects could not be heard.
 *
 * This file replaces it. Everything but the CD functions goes to the
 * system's winmm.dll, loaded by full path, through a jump table
 * (winmm_thunks.h, generated by tools/gen_winmm.py). The CD emulation follows
 * ogg-winmm's behaviour, which the game was shipped with -- device 0xBEEF,
 * one track per TrackNN.ogg, positions in seconds with 4 s for each missing
 * track, one virtual aux device for the volume -- and plays the music
 * through a DirectSound stream using the Vorbis DLLs that come with the game.
 *
 * The CD emulation is based on ogg-winmm:
 *
 * Copyright (c) 2012 Toni Spets <toni.spets@iki.fi>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#include <windows.h>
#include <mmsystem.h>
#include <stdarg.h>
#include <string.h>
#define COBJMACROS
#include <dsound.h>
#include "winmm_thunks.h"

/* ---- pass-through ------------------------------------------------------- */
static HMODULE g_sys=NULL;

/* The system DLL is loaded by full path, so this module keeps its own name
 * without the relative forwarders. Loading from DllMain is safe here: it is a
 * system DLL whose own imports are already resolvable. */
static void load_system_winmm(void){
    char path[MAX_PATH];
    UINT n=GetSystemDirectoryA(path,MAX_PATH);
    if(!n || n+11>=MAX_PATH) return;
    lstrcpyA(path+n,"\\winmm.dll");
    g_sys=LoadLibraryA(path);
    if(!g_sys) return;
    for(int i=0;i<WINMM_THUNKS;i++)
        g_real[i]=(void*)GetProcAddress(g_sys,g_thunkTargets[i].name?g_thunkTargets[i].name
                                              :(LPCSTR)(ULONG_PTR)g_thunkTargets[i].ordinal);
}
typedef MCIERROR (WINAPI *mciCmd_t)(MCIDEVICEID,UINT,DWORD_PTR,DWORD_PTR);
static MCIERROR real_mciSendCommandA(MCIDEVICEID d,UINT m,DWORD_PTR f,DWORD_PTR p){
    mciCmd_t fn=g_sys?(mciCmd_t)(void*)GetProcAddress(g_sys,"mciSendCommandA"):NULL;
    return fn?fn(d,m,f,p):MCIERR_UNRECOGNIZED_COMMAND;
}

/* Build with -DWINMM_DEBUG to log the CD commands to winmm_debug.log. */
static char g_dir[MAX_PATH];             /* this module's folder, with trailing backslash */
#ifdef WINMM_DEBUG
static void wlog(const char* fmt,...){
    char line[512],path[MAX_PATH]; va_list a; va_start(a,fmt);
    int n=wsprintfA(line,"%lu ",GetTickCount());
    n+=wvsprintfA(line+n,fmt,a); va_end(a);
    lstrcpyA(line+n,"\r\n");
    lstrcpyA(path,g_dir); lstrcatA(path,"winmm_debug.log");
    HANDLE h=CreateFileA(path,FILE_APPEND_DATA,FILE_SHARE_READ|FILE_SHARE_WRITE,NULL,OPEN_ALWAYS,FILE_ATTRIBUTE_NORMAL,NULL);
    if(h!=INVALID_HANDLE_VALUE){ DWORD w; WriteFile(h,line,(DWORD)lstrlenA(line),&w,NULL); CloseHandle(h); }
}
#define WLOG(...) wlog(__VA_ARGS__)
static void where(char* out,void* addr){
    HMODULE m=NULL; char name[MAX_PATH]="?";
    if(GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS|GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,(LPCSTR)addr,&m) && m){
        GetModuleFileNameA(m,name,MAX_PATH);
        const char* b=name; for(const char* q=name;*q;q++) if(*q=='\\') b=q+1;
        wsprintfA(out,"%s+0x%lx",b,(DWORD)((BYTE*)addr-(BYTE*)m));
    }else wsprintfA(out,"%p",addr);
}
static LONG CALLBACK veh(PEXCEPTION_POINTERS e){
    static volatile LONG count=0;
    DWORD code=e->ExceptionRecord->ExceptionCode;
    if(code!=EXCEPTION_ACCESS_VIOLATION && code!=EXCEPTION_ILLEGAL_INSTRUCTION && code!=EXCEPTION_INT_DIVIDE_BY_ZERO
       && code!=EXCEPTION_STACK_OVERFLOW) return EXCEPTION_CONTINUE_SEARCH;
    if(InterlockedIncrement(&count)>40) return EXCEPTION_CONTINUE_SEARCH;
    char at[300],st[900]=""; int n=0;
    where(at,e->ExceptionRecord->ExceptionAddress);
    DWORD* sp=(DWORD*)e->ContextRecord->Esp;
    for(int i=0,found=0;i<256 && found<8;i++){
        MEMORY_BASIC_INFORMATION mbi;
        if(!VirtualQuery(sp+i,&mbi,sizeof mbi) || mbi.State!=MEM_COMMIT) break;
        HMODULE m=NULL;
        if(sp[i]>0x10000 && GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS|GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,(LPCSTR)(DWORD_PTR)sp[i],&m) && m){
            char w[300]; where(w,(void*)(DWORD_PTR)sp[i]);
            if(n+lstrlenA(w)+3<(int)sizeof st){ lstrcpyA(st+n," < "); lstrcpyA(st+n+3,w); n+=3+lstrlenA(w); found++; }
        }
    }
    wlog("EXCEPTION 0x%08lx at %s T%lu access %lu addr 0x%08lx eax=%08lx ecx=%08lx edx=%08lx esi=%08lx edi=%08lx stack%s",
         code,at,GetCurrentThreadId(),
         e->ExceptionRecord->NumberParameters>0?(DWORD)e->ExceptionRecord->ExceptionInformation[0]:0,
         e->ExceptionRecord->NumberParameters>1?(DWORD)e->ExceptionRecord->ExceptionInformation[1]:0,
         e->ContextRecord->Eax,e->ContextRecord->Ecx,e->ContextRecord->Edx,e->ContextRecord->Esi,e->ContextRecord->Edi,st);
    return EXCEPTION_CONTINUE_SEARCH;
}
#else
#define WLOG(...) ((void)0)
#endif

/* ---- tracks ------------------------------------------------------------- */
#define MAGIC_DEVICEID 0xBEEF
#define MAX_TRACKS 99
typedef struct { char path[MAX_PATH]; unsigned length,position; } Track;   /* seconds */
static Track g_tracks[MAX_TRACKS];
static int g_firstTrack=-1,g_lastTrack=0,g_numTracks=0;
static DWORD g_timeFormat=MCI_FORMAT_TMSF;


typedef int    (__cdecl *ov_fopen_t)(const char*,void*);
typedef void*  (__cdecl *ov_info_t)(void*,int);
typedef long   (__cdecl *ov_read_t)(void*,char*,int,int,int,int,int*);
typedef double (__cdecl *ov_time_total_t)(void*,int);
typedef int    (__cdecl *ov_clear_t)(void*);
static ov_fopen_t p_ov_fopen; static ov_info_t p_ov_info; static ov_read_t p_ov_read;
static ov_time_total_t p_ov_time_total; static ov_clear_t p_ov_clear;
#define VF_BYTES 16384                   /* OggVorbis_File is well under 1 KB on 32-bit */
#define OV_HOLE (-3)

static int load_vorbis(void){
    if(p_ov_read) return 1;
    char path[MAX_PATH];
    if(lstrlenA(g_dir)+24>=MAX_PATH) return 0;
    lstrcpyA(path,g_dir); lstrcatA(path,"libvorbisfile-3.dll");
    HMODULE m=LoadLibraryExA(path,NULL,LOAD_WITH_ALTERED_SEARCH_PATH);
    if(!m) return 0;
    p_ov_fopen=(ov_fopen_t)(void*)GetProcAddress(m,"ov_fopen");
    p_ov_info=(ov_info_t)(void*)GetProcAddress(m,"ov_info");
    p_ov_time_total=(ov_time_total_t)(void*)GetProcAddress(m,"ov_time_total");
    p_ov_clear=(ov_clear_t)(void*)GetProcAddress(m,"ov_clear");
    p_ov_read=(ov_read_t)(void*)GetProcAddress(m,"ov_read");
    if(!p_ov_fopen || !p_ov_info || !p_ov_time_total || !p_ov_clear || !p_ov_read){ p_ov_read=NULL; return 0; }
    return 1;
}
static unsigned track_length(const char* path){
    static BYTE vf[VF_BYTES];
    if(GetFileAttributesA(path)==INVALID_FILE_ATTRIBUTES) return 0;
    ZeroMemory(vf,sizeof vf);
    if(p_ov_fopen(path,vf)!=0) return 0;
    int s=(int)p_ov_time_total(vf,-1);       /* signed: no libgcc helper */
    p_ov_clear(vf);
    return s>0?(unsigned)s:0;
}
static void scan_tracks(void){
    static int scanned=0;
    if(scanned) return;
    scanned=1;
    if(!load_vorbis()) return;
    unsigned position=0;
    for(int i=0;i<MAX_TRACKS;i++){
        Track* t=&g_tracks[i];
        if(lstrlenA(g_dir)+18>=MAX_PATH){ t->path[0]=0; position+=4; continue; }
        wsprintfA(t->path,"%sMUSIC\\Track%02d.ogg",g_dir,i);
        t->length=track_length(t->path);
        t->position=position;
        if(t->length<4){ t->path[0]=0; position+=4; }   /* missing tracks count as 4 s data tracks */
        else{
            if(g_firstTrack==-1) g_firstTrack=i;
            g_numTracks++; g_lastTrack=i; position+=t->length;
        }
    }
}

/* ---- player: one thread, one DirectSound stream ------------------------- */
typedef HRESULT (WINAPI *DSCreate_t)(LPCGUID,LPDIRECTSOUND*,LPUNKNOWN);
static CRITICAL_SECTION g_cs;
static HANDLE g_thread=NULL,g_wake=NULL;
static volatile LONG g_playing=0;        /* what MCI_STATUS_MODE reports */
static volatile LONG g_volume=100;       /* 0..100 from auxSetVolume */
static int g_reqFirst=-1,g_reqLast=-1;   /* pending play request */
static volatile LONG g_reqSeq=0,g_stopSeq=0;

typedef struct {
    LPDIRECTSOUND ds; LPDIRECTSOUNDBUFFER buf;
    DWORD size,block,lead,rate,channels;
    DWORD wpos,lastPlay; ULONGLONG written,played;
} Stream;

static HWND game_window(void);
static int stream_open(Stream* s,DWORD rate,DWORD channels){
    static DSCreate_t create=NULL;
    if(!create){
        HMODULE m=LoadLibraryA("dsound.dll");
        create=m?(DSCreate_t)(void*)GetProcAddress(m,"DirectSoundCreate"):NULL;
        if(!create) return 0;
    }
    if(!s->ds){
        if(FAILED(create(NULL,&s->ds,NULL))){ s->ds=NULL; return 0; }
        IDirectSound_SetCooperativeLevel(s->ds,game_window(),DSSCL_NORMAL);
    }
    WAVEFORMATEX f; ZeroMemory(&f,sizeof f);
    f.wFormatTag=WAVE_FORMAT_PCM; f.nChannels=(WORD)channels; f.nSamplesPerSec=rate; f.wBitsPerSample=16;
    f.nBlockAlign=(WORD)(channels*2); f.nAvgBytesPerSec=rate*f.nBlockAlign;
    DSBUFFERDESC d; ZeroMemory(&d,sizeof d); d.dwSize=sizeof d;
    d.dwFlags=DSBCAPS_GETCURRENTPOSITION2|DSBCAPS_GLOBALFOCUS;
    s->block=f.nBlockAlign;
    s->size=f.nAvgBytesPerSec/s->block*s->block;             /* one second */
    s->lead=s->size/4/s->block*s->block;                      /* keep 250 ms ahead */
    d.dwBufferBytes=s->size; d.lpwfxFormat=&f;
    if(FAILED(IDirectSound_CreateSoundBuffer(s->ds,&d,&s->buf,NULL))){ s->buf=NULL; return 0; }
    void *p1,*p2; DWORD n1,n2;
    if(SUCCEEDED(IDirectSoundBuffer_Lock(s->buf,0,s->size,&p1,&n1,&p2,&n2,0))){
        memset(p1,0,n1); if(p2) memset(p2,0,n2);
        IDirectSoundBuffer_Unlock(s->buf,p1,n1,p2,n2);
    }
    s->rate=rate; s->channels=channels; s->wpos=0; s->lastPlay=0; s->written=0; s->played=0;
    IDirectSoundBuffer_SetCurrentPosition(s->buf,0);
    IDirectSoundBuffer_Play(s->buf,0,0,DSBPLAY_LOOPING);
    return 1;
}
static void stream_close_buffer(Stream* s){
    if(s->buf){ IDirectSoundBuffer_Stop(s->buf); IDirectSoundBuffer_Release(s->buf); s->buf=NULL; }
}
static void stream_update(Stream* s){
    DWORD play=0,wc=0;
    if(FAILED(IDirectSoundBuffer_GetCurrentPosition(s->buf,&play,&wc))) return;
    s->played+=(play+s->size-s->lastPlay)%s->size; s->lastPlay=play;
    if(s->played>s->written){ s->written=s->played; s->wpos=play; }   /* underrun: go on at the cursor */
}
/* n bytes of PCM, or silence when src is NULL, at the write position */
static void stream_put(Stream* s,const BYTE* src,DWORD n){
    void *p1,*p2; DWORD n1,n2;
    if(!n || FAILED(IDirectSoundBuffer_Lock(s->buf,s->wpos,n,&p1,&n1,&p2,&n2,0))) return;
    if(src){ memcpy(p1,src,n1); if(p2) memcpy(p2,src+n1,n2); }
    else   { memset(p1,0,n1); if(p2) memset(p2,0,n2); }
    IDirectSoundBuffer_Unlock(s->buf,p1,n1,p2,n2);
    s->written+=n1+n2; s->wpos=(s->wpos+n1+n2)%s->size;
}
/* stop at once: silence everything already queued ahead of the cursor */
static void stream_flush(Stream* s){
    DWORD play=0,wc=0;
    if(FAILED(IDirectSoundBuffer_GetCurrentPosition(s->buf,&play,&wc))) return;
    s->played+=(play+s->size-s->lastPlay)%s->size; s->lastPlay=play;
    s->wpos=play; s->written=s->played;
    stream_put(s,NULL,s->size-s->block);
    s->wpos=play; s->written=s->played;
}

static DWORD WINAPI player_thread(LPVOID arg){
    (void)arg;
    static BYTE vf[VF_BYTES];
    static BYTE pcm[65536];
    Stream s; ZeroMemory(&s,sizeof s);
    LONG seenReq=0,seenStop=0;
    int open=0,cur=-1,last=-1,draining=0;
    ULONGLONG endMark=0;
    for(;;){
        WaitForSingleObject(g_wake,10);
        EnterCriticalSection(&g_cs);
        LONG req=g_reqSeq,stop=g_stopSeq; int rf=g_reqFirst,rl=g_reqLast;
        LeaveCriticalSection(&g_cs);
        if(stop!=seenStop){
            seenStop=stop;
            if(open){ p_ov_clear(vf); open=0; }
            draining=0; cur=-1;
            if(s.buf) stream_flush(&s);
        }
        if(req!=seenReq){
            seenReq=req;
            if(open){ p_ov_clear(vf); open=0; }
            if(s.buf) stream_flush(&s);
            cur=rf; last=rl; draining=0;
        }
        /* open the next track that exists */
        while(!open && cur>=0 && cur<=last){
            ZeroMemory(vf,sizeof vf);
            if(g_tracks[cur].path[0] && p_ov_fopen(g_tracks[cur].path,vf)==0){
                int* vi=(int*)p_ov_info(vf,-1);         /* vorbis_info: version, channels, rate */
                if(vi && vi[1]>0 && vi[1]<=2 && vi[2]>0){
                    if(!s.buf || s.rate!=(DWORD)vi[2] || s.channels!=(DWORD)vi[1]){
                        stream_close_buffer(&s);
                        if(!stream_open(&s,(DWORD)vi[2],(DWORD)vi[1])){ p_ov_clear(vf); cur=-1; break; }
                    }
                    open=1;
                    WLOG("track %d open: %d Hz, %d ch, stream %s",cur,vi[2],vi[1],s.buf?"ok":"none");
                    break;
                }
                p_ov_clear(vf);
            }
            cur++;
        }
        if(!open && cur>last && !draining && cur!=-1){ draining=1; endMark=s.buf?s.written:0; cur=-1; }
        if(!s.buf){
            if(draining){ draining=0; if(g_reqSeq==seenReq) InterlockedExchange(&g_playing,0); }
            continue;
        }
        stream_update(&s);
        for(;;){
            DWORD ahead=(DWORD)(s.written-s.played);
            if(!open){
                if(ahead<s.lead) stream_put(&s,NULL,(s.lead-ahead)/s.block*s.block);
                break;
            }
            if(ahead>=s.lead) break;
            DWORD want=(s.lead-ahead)/s.block*s.block;
            if(want>sizeof pcm) want=sizeof pcm/s.block*s.block;
            DWORD got=0;
            while(got<want){
                int bs=0;
                long r=p_ov_read(vf,(char*)pcm+got,(int)(want-got),0,2,1,&bs);
                if(r==OV_HOLE) continue;
                if(r<=0) break;
                got+=(DWORD)r;
            }
            got=got/s.block*s.block;
            if(got){
                LONG vol=g_volume;
                if(vol<100){
                    short* p=(short*)pcm; DWORD n=got/2;
                    for(DWORD k=0;k<n;k++) p[k]=(short)(p[k]*vol/100);
                }
                stream_put(&s,pcm,got);
            }
            if(got<want){                                /* end of this track */
                p_ov_clear(vf); open=0; cur++;
                break;
            }
        }
        if(draining && s.played>=endMark){ draining=0; if(g_reqSeq==seenReq) InterlockedExchange(&g_playing,0); }
    }
    return 0;
}
static void start_player(void){
    static volatile LONG started=0;
    if(InterlockedExchange(&started,1)) return;
    g_wake=CreateEventA(NULL,FALSE,FALSE,NULL);
    g_thread=CreateThread(NULL,0,player_thread,NULL,0,NULL);
}
static void play_tracks(int first,int last){
    if(!g_numTracks) return;
    EnterCriticalSection(&g_cs);
    g_reqFirst=first; g_reqLast=last; g_reqSeq++;
    LeaveCriticalSection(&g_cs);
    InterlockedExchange(&g_playing,1);
    SetEvent(g_wake);
}
static void stop_tracks(void){
    InterlockedExchange(&g_playing,0);
    EnterCriticalSection(&g_cs); g_stopSeq++; LeaveCriticalSection(&g_cs);
    if(g_wake) SetEvent(g_wake);
}

typedef struct { DWORD pid; HWND found; } WinSearch;
static BOOL CALLBACK find_window(HWND h,LPARAM p){
    WinSearch* w=(WinSearch*)p; DWORD pid=0;
    GetWindowThreadProcessId(h,&pid);
    if(pid==w->pid && IsWindowVisible(h)){ w->found=h; return FALSE; }
    return TRUE;
}
static HWND game_window(void){
    WinSearch w={GetCurrentProcessId(),NULL};
    EnumWindows(find_window,(LPARAM)&w);
    return w.found?w.found:GetDesktopWindow();
}

/* ---- MCI, as ogg-winmm answers it --------------------------------------- */
static MCIERROR mci_command(MCIDEVICEID dev,UINT msg,DWORD_PTR flags,DWORD_PTR param);
MCIERROR WINAPI i82_mciSendCommandA(MCIDEVICEID dev,UINT msg,DWORD_PTR flags,DWORD_PTR param){
    MCIERROR r=mci_command(dev,msg,flags,param);
    WLOG("mciSendCommandA dev=%u msg=0x%x flags=0x%lx -> %lu%s",dev,msg,(DWORD)flags,r,
         (msg==MCI_STATUS&&param)?" (status)":"");
    return r;
}
static MCIERROR mci_command(MCIDEVICEID dev,UINT msg,DWORD_PTR flags,DWORD_PTR param){
    if(msg==MCI_OPEN && param){
        LPMCI_OPEN_PARMSA p=(LPMCI_OPEN_PARMSA)param;
        int cd=0;
        if(flags&MCI_OPEN_TYPE_ID) cd=LOWORD((DWORD_PTR)p->lpstrDeviceType)==MCI_DEVTYPE_CD_AUDIO;
        else if((flags&MCI_OPEN_TYPE) && p->lpstrDeviceType) cd=!lstrcmpiA(p->lpstrDeviceType,"cdaudio");
        if(cd){
            scan_tracks(); start_player();
            p->wDeviceID=MAGIC_DEVICEID;
            return 0;
        }
    }
    if(dev!=MAGIC_DEVICEID && dev!=0 && dev!=0xFFFFFFFF)
        return real_mciSendCommandA(dev,msg,flags,param);

    if(msg==MCI_SET && param && (flags&MCI_SET_TIME_FORMAT))
        g_timeFormat=((LPMCI_SET_PARMS)param)->dwTimeFormat;

    if(msg==MCI_CLOSE) stop_tracks();

    if(msg==MCI_PLAY && param){
        LPMCI_PLAY_PARMS p=(LPMCI_PLAY_PARMS)param;
        static int first=-1,last=-1;
        if(flags&MCI_FROM){
            if(g_timeFormat==MCI_FORMAT_TMSF) first=MCI_TMSF_TRACK(p->dwFrom);
            else if(g_timeFormat==MCI_FORMAT_MILLISECONDS){
                first=0;
                for(int i=0;i<MAX_TRACKS;i++) if(g_tracks[i].position==p->dwFrom/1000) first=i;
            }else first=(int)p->dwFrom;
            if(first<g_firstTrack) first=g_firstTrack;
            if(first>g_lastTrack) first=g_lastTrack;
            last=first;
        }
        if(flags&MCI_TO){
            if(g_timeFormat==MCI_FORMAT_TMSF) last=MCI_TMSF_TRACK(p->dwTo);
            else if(g_timeFormat==MCI_FORMAT_MILLISECONDS){
                last=first;
                for(int i=first<0?0:first;i<MAX_TRACKS;i++)
                    if(g_tracks[i].position+g_tracks[i].length>p->dwFrom/1000){ last=i; break; }
            }else last=(int)p->dwTo;
            if(last<first) last=first;
            if(last>g_lastTrack) last=g_lastTrack;
        }
        if(first!=0 && (flags&MCI_FROM)) play_tracks(first,last);
    }

    if(msg==MCI_STOP) stop_tracks();

    if(msg==MCI_STATUS && param){
        LPMCI_STATUS_PARMS p=(LPMCI_STATUS_PARMS)param;
        p->dwReturn=0;
        if(flags&MCI_STATUS_ITEM){
            DWORD t=(DWORD)p->dwTrack<MAX_TRACKS?(DWORD)p->dwTrack:0;
            switch(p->dwItem){
            case MCI_STATUS_LENGTH:{
                unsigned sec=g_tracks[t].length;
                if(sec) p->dwReturn=g_timeFormat==MCI_FORMAT_MILLISECONDS?sec*1000:MCI_MAKE_MSF(sec/60,sec%60,0);
                break; }
            case MCI_STATUS_MEDIA_PRESENT: p->dwReturn=g_lastTrack>0; break;
            case MCI_STATUS_NUMBER_OF_TRACKS: p->dwReturn=g_numTracks; break;
            case MCI_STATUS_POSITION: if(flags&MCI_TRACK) p->dwReturn=g_tracks[t].position*1000; break;
            case MCI_STATUS_MODE: p->dwReturn=g_playing?MCI_MODE_PLAY:MCI_MODE_STOP; break;
            }
        }
    }
    return 0;
}
/* "play cd from <n> to <n>" */
static int parse_number(const char** s,int* out){
    const char* p=*s; int v=0,any=0;
    while(*p==' ') p++;
    while(*p>='0' && *p<='9'){ v=v*10+(*p-'0'); p++; any=1; }
    *s=p; *out=v;
    return any;
}
static int parse_play(const char* cmd,int* from,int* to){
    const char* p=strstr(cmd,"play cd from ");
    if(!p) return 0;
    p+=13;
    if(!parse_number(&p,from)) return 0;
    while(*p==' ') p++;
    if(strncmp(p,"to ",3)) return 0;
    p+=3;
    return parse_number(&p,to);
}
MCIERROR WINAPI i82_mciSendStringA(LPCSTR cmd,LPSTR ret,UINT n,HWND cb){
    (void)cb;
    if(!cmd) return 0;
    if(strstr(cmd,"sysinfo")){ if(ret && n>2) lstrcpyA(ret,"cd"); return 0; }
    if(strstr(cmd,"stop cd")){ i82_mciSendCommandA(MAGIC_DEVICEID,MCI_STOP,0,0); return 0; }
    int from=-1,to=-1;
    if(parse_play(cmd,&from,&to)){
        static MCI_PLAY_PARMS p;
        p.dwFrom=(DWORD)from; p.dwTo=(DWORD)to;
        i82_mciSendCommandA(MAGIC_DEVICEID,MCI_PLAY,MCI_FROM|MCI_TO,(DWORD_PTR)&p);
    }
    return 0;
}

/* ---- aux: one virtual CD device carrying the music volume --------------- */
UINT WINAPI i82_auxGetNumDevs(void){ return 1; }
MMRESULT WINAPI i82_auxGetDevCapsA(UINT_PTR dev,LPAUXCAPSA caps,UINT cb){
    (void)dev;
    if(!caps || cb<sizeof(AUXCAPSA)) return MMSYSERR_INVALPARAM;
    ZeroMemory(caps,sizeof *caps);
    caps->wMid=2; caps->wPid=401; caps->vDriverVersion=1;           /* MM_CREATIVE, CD aux */
    lstrcpyA(caps->szPname,"I82 virtual CD");
    caps->wTechnology=AUXCAPS_CDAUDIO; caps->dwSupport=AUXCAPS_VOLUME;
    return MMSYSERR_NOERROR;
}
MMRESULT WINAPI i82_auxGetVolume(UINT dev,LPDWORD vol){
    (void)dev;
    if(vol) *vol=0;
    return MMSYSERR_NOERROR;
}
MMRESULT WINAPI i82_auxSetVolume(UINT dev,DWORD vol){
    (void)dev;
    InterlockedExchange(&g_volume,(LONG)(LOWORD(vol)*100u/65535u));
    WLOG("auxSetVolume 0x%08lx -> %ld",vol,g_volume);
    return MMSYSERR_NOERROR;
}

BOOL WINAPI DllMain(HINSTANCE h,DWORD reason,LPVOID r){
    (void)r;
    if(reason==DLL_PROCESS_ATTACH){
        DisableThreadLibraryCalls(h);
        InitializeCriticalSection(&g_cs);
        DWORD n=GetModuleFileNameA(h,g_dir,MAX_PATH);
        if(n && n<MAX_PATH){ while(n && g_dir[n-1]!='\\') n--; g_dir[n]=0; } else g_dir[0]=0;
        load_system_winmm();
#ifdef WINMM_DEBUG
        AddVectoredExceptionHandler(1,veh);
        wlog("loaded, system winmm %p",(void*)g_sys);
#endif
    }
    return TRUE;
}
