"""Generate winmm_thunks.h and winmm.def from the system's 32-bit winmm.dll.

Every export of the system DLL becomes a jump through a pointer that
winmm.c fills at load time, keeping the system's ordinals. The functions
winmm.c implements itself are exported under their own names instead.

Usage (from the repository root, on Windows):
    python tools/gen_winmm.py
"""
import os
import struct

SYSTEM = os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "SysWOW64", "winmm.dll")
OWN = {"mciSendCommandA": "i82_mciSendCommandA", "mciSendStringA": "i82_mciSendStringA",
       "auxGetNumDevs": "i82_auxGetNumDevs", "auxGetDevCapsA": "i82_auxGetDevCapsA",
       "auxGetVolume": "i82_auxGetVolume", "auxSetVolume": "i82_auxSetVolume"}


def exports(path):
    b = open(path, "rb").read()
    pe = struct.unpack_from("<I", b, 0x3C)[0]
    nsec = struct.unpack_from("<H", b, pe + 6)[0]
    opt = pe + 24
    optsize = struct.unpack_from("<H", b, pe + 20)[0]
    rva = struct.unpack_from("<I", b, opt + 96)[0]              # PE32 export directory
    secs = [struct.unpack_from("<8sIIII", b, opt + optsize + 40 * i) for i in range(nsec)]

    def off(r):
        for _, vs, va, rs, ro in secs:
            if va <= r < va + max(vs, rs):
                return r - va + ro
    d = off(rva)
    base, nfun, nnames, afun, aname, aord = struct.unpack_from("<IIIIII", b, d + 16)
    named = {}
    for i in range(nnames):
        name = b[off(struct.unpack_from("<I", b, off(aname) + 4 * i)[0]):].split(b"\0")[0].decode()
        named[struct.unpack_from("<H", b, off(aord) + 2 * i)[0] + base] = name
    ordinals = [base + i for i in range(nfun) if struct.unpack_from("<I", b, off(afun) + 4 * i)[0]]
    return ordinals, named


ordinals, named = exports(SYSTEM)
thunks = [o for o in ordinals if named.get(o) not in OWN]
here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

h = ["/* Generated by tools/gen_winmm.py from the system's 32-bit winmm.dll. Do not edit. */",
     "#define WINMM_THUNKS %d" % len(thunks),
     "static const struct { const char* name; WORD ordinal; } g_thunkTargets[WINMM_THUNKS]={"]
for o in thunks:
    h.append('    {%s,%d},' % ('"%s"' % named[o] if o in named else "NULL", o))
h.append("};")
h.append("void* g_real[WINMM_THUNKS];")
h.append("__asm__(\".text\\n\"")
for i, o in enumerate(thunks):
    h.append('    ".globl _thunk_%d\\n_thunk_%d: jmp *_g_real+%d\\n"' % (i, i, 4 * i))
h.append(");")
open(os.path.join(here, "winmm_thunks.h"), "w", newline="\r\n").write("\n".join(h) + "\n")

d = ["; Generated by tools/gen_winmm.py from the system's 32-bit winmm.dll. Do not edit.",
     "LIBRARY winmm.dll", "EXPORTS"]
for i, o in enumerate(thunks):
    d.append("    %s=thunk_%d @%d" % (named[o], i, o) if o in named else "    thunk_%d @%d NONAME" % (i, o))
for o in ordinals:
    if named.get(o) in OWN:
        d.append("    %s=%s @%d" % (named[o], OWN[named[o]], o))
open(os.path.join(here, "winmm.def"), "w", newline="\r\n").write("\n".join(d) + "\n")
print("%d exports, %d thunks, %d own" % (len(ordinals), len(thunks), len(ordinals) - len(thunks)))
